general:
  executed: "&6%troll.name%&a executed!"
  offlineError: "&cYour target is offline!"
  warningsEnabled: true
  warn: "&cThis troll can: %troll.warnings%"
  warnings:
    kill: "kill player"
    world: "change world"
    inventory: "change inventory"
# you can use changer if you want change description, usage or default args.
changer:

